function [mesh_facade3D]=generateSurfaceCityMesh(mesh2D,fields,...
    minElevFromGround,translationVector,...
    doTreatSpecialBuildings,typeTreatSpecialBuildings,...
    meshFacadesWithQuads,idealizationLevel,...
    exportStepsToParaview)

if(strcmp(idealizationLevel,'block'))
    [mesh_facade3D]=generateSurface_blocks(mesh2D,fields,...
        minElevFromGround,translationVector,...
        doTreatSpecialBuildings,typeTreatSpecialBuildings,...
        meshFacadesWithQuads,idealizationLevel,...
        exportStepsToParaview);
elseif(strcmp(idealizationLevel,'building'))
    [mesh_facade3D]=generateSurface_buildings(mesh2D,fields,...
        minElevFromGround,translationVector,...
        doTreatSpecialBuildings,typeTreatSpecialBuildings,...
        meshFacadesWithQuads,idealizationLevel,...
        exportStepsToParaview);
else
    idealizationLevel
    error('Not implemented idealization level')
end

