
function [adaptStep]=createBamgString(bamg_exe,mesh_input,mesh_output,...
    solution_input,data,solution_output,geo_input)

    if(nargin>6)
        bamg_exe = [bamg_exe geo_input];
    end

    data_strings   = createStringsFromData(data);
    
    command_adapt  = [' -Mbb ' solution_input];
    
    %command_interp = [' -rbb ' solution_input ' -wbb ' solution_output];
    command_interp = [ ' -wbb ' solution_output];
    %command_interp = [' '];%' -wbb ' solution_output];

    
    command_inputMesh = [ ' -b ' mesh_input];
    %command_inputMesh = [ ' -r ' mesh_input];
    
    command_verbose = ' -v 1 ';
    command_verbose = ' -v 10 ';
    
    adaptStep =[bamg_exe  ...
                command_inputMesh ...
                command_adapt ...
                data_strings ...
                ' -o '  mesh_output ...
                command_interp ...
                command_verbose];
            
%     adaptStep =[bamg_exe  ...
%                 command_inputMesh ...
%                 command_adapt ...
%                 data_strings ...
%                 geo_input ...
%                 ' -o '  mesh_output ...
%                 command_interp ];
    
%     adaptStep =[bamg_exe  ...
%                 command_inputMesh ...
%                 command_adapt ...
%                 data_strings ...
%                 ' -o '  mesh_output ...
%                 command_interp ];
end

% !/usr/local/ff++/mpich3/bin/bamg 
% -g ./temps/exact_inp.msh 
% -r ./temps/temp_mesh_input.msh 
% -Mbb ./temps/temp_multiSol_inpput.bb 
% -coef 1 -ratio 0 -errg 0.01 -err 0.01 -iso  -hmin 0.45 -hmax 6.25 -anisomax 5  -nbv 1000000 
% -o ./temps/temp_mesh_output.msh 
