function [data_strings]=createStringsFromData(data)


    switch data.iso
        case '1'
            text_iso = ' -iso ';
        case '0'
            text_iso = ' -aniso';
        otherwise
            error('Wrong value for iso');
    end
    
    switch data.hmin
        case '0'
            text_hmin = ' ';
        otherwise
            text_hmin = [' -hmin ' data.hmin];
    end
    
    switch data.hmax
        case '0'
            text_hmax = ' ';
        otherwise
            text_hmax = [' -hmax ' data.hmax];
    end
    
    switch data.anisomax
        case '0'
            text_anisomax = ' ';
        otherwise
            text_anisomax = [' -anisomax ' data.anisomax];
    end
    
    if(isfield(data,'relErr'))
        %text_relErr = [' -RelError ' data.relErr]
        error('not possible')
    else
        text_relErr = '  ';
    end

    data_strings = [' -coef ' data.coef...
                    ' -ratio ' data.ratio...
                    ' -errg ' data.errg...
                    ' -err ' data.err...
                    text_iso...
                    text_hmin ...
                    text_hmax...
                    text_anisomax...
                    text_relErr...
                    ' -nbv ' data.nbv ];

    data_strings = [' -err ' data.err...
                    text_iso...
                    text_hmin ...
                    text_hmax...
                    ' -nbv ' data.nbv ];

    data_strings = [' -err ' data.err...
                text_iso...
                text_anisomax...
                text_hmin ...
                text_hmax...
                ' -nbv ' data.nbv ];
    
%     data_strings = [' -coef ' data.coef ...
%                     ' -ratio ' data.ratio ...
%                     ' -errg ' data.errg ...
%                     ' -AbsError -NoRescaling -NbJacobi 2  -NbSmooth 5  ' ...
%                     text_iso  ...
%                     text_hmin ...
%                     text_hmax ...
%                     text_anisomax ...
%                     text_relErr...
%                     ' -nbv ' data.nbv ];


