%creates the instructions to Bamg

function [adaptativeStep]=instructionBamg3(bamg_exe,msh,data,f_file)
    switch data.iso
        case '1'
            if data.hmin == '0'
                if data.hmax == '0'
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                else
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                end
            else
                if data.hmax == '0'
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                else
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                end
            end
            
        case '0'
            if data.hmin == '0'
                if data.hmax == '0'
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                else
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                end
            else
                if data.hmax == '0'
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                else
                    if data.anisomax == '0'
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    else
                        adaptativeStep = [ ...
                            bamg_exe ' -b ' msh ...
                            ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
                            ' -Mbb ' f_file ...
                            ' -o '  msh  ' -rbb ./temps/z_temp_sol.bb ' ' -wbb ./temps/z_temp_sol.bb ' ];
                    end
                end
            end
            
        otherwise
            error('Wrong value for iso');
    end
end