%creates the instructions to Bamg

function [adaptativeStep]=instructionBamg(bamg_exe,mesh_input,mesh_output,metric_input,data)
    switch data.iso
        case '1'
            text_iso = ' -iso ';
        case '0'
            text_iso = ' ';
        otherwise
            error('Wrong value for iso');
    end
    
    switch data.hmin
        case '0'
            text_hmin = ' ';
        otherwise
            text_hmin = [' -hmin ' data.hmin];
    end
    
    switch data.hmax
        case '0'
            text_hmax = ' ';
        otherwise
            text_hmax = [' -hmax ' data.hmax];
    end
    
    switch data.anisomax
        case '0'
            text_anisomax = ' ';
        otherwise
            text_anisomax = [' -anisomax ' data.anisomax];
    end
    
    adaptativeStep = [bamg_exe ' -b ' mesh_input ...
                        ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err text_iso text_hmin text_hmax text_anisomax ' -nbv ' data.nbv ...
                        ' -Mbb ' metric_input ...
                        ' -o '  mesh_output ];

%     switch data.iso
%         case '1'
%             if data.hmin == '0'
%                 if data.hmax == '0'
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 else
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 end
%             else
%                 if data.hmax == '0'
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 else
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -iso ' ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 end
%             end
%             
%         case '0'
%             if data.hmin == '0'
%                 if data.hmax == '0'
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 else
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 end
%             else
%                 if data.hmax == '0'
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 else
%                     if data.anisomax == '0'
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     else
%                         adaptativeStep = [ ...
%                             bamg_exe ' -b ' msh ...
%                             ' -coef ' data.coef ' -ratio ' data.ratio ' -hmin ' data.hmin ' -hmax ' data.hmax ' -errg ' data.errg ' -err ' data.err ' -anisomax ' data.anisomax  ' -nbv ' data.nbv  ...
%                             ' -Mbb ' f_file ...
%                             ' -o '  msh ];
%                     end
%                 end
%             end
%             
%         otherwise
%             error('Wrong value for iso');
%     end
end